# GitLab CI/CD pipeline for deploying a plain HTML site
# Full project: https://gitlab.com/pages/plain-html

image: busybox

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Deploying site to: $CI_PAGES_URL"
    - echo "Logging deployment for reference."
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
